### ISSUE TITLE
Button Control Label doesn't update if Label is bound to table control

### ISSUE THREAD

**Issue by easybeat** [BIDSL/PCFControls#7]
Hi

I'm facing a problem that the button label is not refreshed when I change the bound control value.

Is there a way to force a refresh of the button?

Kind regards
Beat

**Comment by BIDSL** [comment]
Thanks for writing to me. I just fixed the issue. You may download the latest solution and install it.
Please do a hard refresh of the page and let me know if that worked.

**Comment by BIDSL** [comment]
Marking this ticket as closed. Feel free to create new ticket if needed.
