### ISSUE TITLE
Set Button Text to Column Label (& by Language)

### ISSUE THREAD

**Issue by elirickert** [BIDSL/PCFControls#8]
Hey Maniraj 

Do you think it would be possible to bind the Button label to the column display name instead of the column value? And would that allow to automatically display the display name of the current language if the field is translated?

In any case thank you very much for the cool Button control implementation.

Best, Eli

**Comment by BIDSL** [comment]
Hi Eli, 
Thanks for your comment. Yes it is possible. I will update the component over this weekend and publish it.

-Maniraj.

**Comment by elirickert** [comment]
Hi Maniraj

Sorry to bother, but is there an update from your side. If not, is there a possibility that I could contribute something?

Best, Eli

**Comment by BIDSL** [comment]
Hi Eli

Thanks for reaching out.

Sorry, I didn't get a chance to work on that. Today I will try to update and publish the latest solution and source code.

I will let you know over the email.

Maniraj.

Regards,
Maniraj. K.V.
________________________________

**Comment by BIDSL** [comment]
Hi Elie

Apologies
Still I haven't fixed it. Will work on it tomorrow or will share the latest source code.

Regards
Maniraj.

Regards,
Maniraj. K.V.
________________________________

**Comment by BIDSL** [comment]
Hi Elie,

Issue fixed and updated the solutions. Please let me know if it works for you.

Thanks.

**Comment by elirickert** [comment]
thank you so much for the swift update!

Sadly when I leave the label value empty (as I understood the release notes this would be the way to bind it to the column name value) I get the following issue:
![image](https://github.com/BIDSL/PCFControls/assets/55528987/5d1cc1bf-7997-460b-83d8-501eb771eac7)

Which renders on the published form like follows:
![image](https://github.com/BIDSL/PCFControls/assets/55528987/b9ff991c-0b06-4b98-911d-e9134089fe7f)

Do you have an idea why this happens?

**Comment by BIDSL** [comment]
Hi Eli

Can you reache me on ***@***.*** we can have a quick call to see the issue?

Regards,
Maniraj. K.V.
________________________________

**Comment by elirickert** [comment]
sadly i cannot see your email, it is just ***@***.***

maybe you can join this call: https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZDViYTZjZWUtMzU0ZC00ZTE3LTg1ZTQtNTdhMWM2MGFmMzIx%40thread.v2/0?context=%7b%22Tid%22%3a%22be4f2c2f-7478-413e-9569-aa6278d6f7f1%22%2c%22Oid%22%3a%226e340d00-685a-445c-8fd8-b5c018bec5fd%22%7d

?

**Comment by elirickert** [comment]
Thank you so much it works now!
